- name: Deploy Node.js App on Private EC2
  hosts: app_servers
  become: yes
  strategy: linear
  serial: 1
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Purge existing nodejs and libnode-dev to prevent conflicts
      shell: |
        sudo apt-get purge -y nodejs npm nodejs-doc libnode-dev || true
        sudo apt-get autoremove -y
        sudo rm -rf /usr/lib/node_modules
        sudo rm -rf /usr/bin/node
        sudo rm -rf /usr/bin/npm
        sudo rm -rf /usr/include/node
      become: yes

    - name: Install dependencies for NodeSource
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present

    - name: Add NodeSource repository for Node.js 18
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -

    - name: Install Node.js 18
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Verify Node.js version
      command: node -v
      register: node_version
      
    - debug:
        msg: "Node.js version is {{ node_version.stdout }}"

    - name: Install git
      apt:
        name: git
        state: present

    - name: Ensure app directory exists
      file:
        path: /var/www/node-app
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Clone the Node.js application from GitHub
      git:
        repo: 'https://github.com/AlaaElgazwy/node-aws-app.git'
        dest: /var/www/node-app
        version: main
        force: yes

    - name: Clean npm cache
      command: npm cache clean --force
      args:
        chdir: /var/www/node-app

    - name: Remove old node_modules and package-lock.json
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/node-app/node_modules
        - /var/www/node-app/package-lock.json

    - name: Install application dependencies
      npm:
        path: /var/www/node-app
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Stop existing PM2 process if running
      command: pm2 stop backend-app
      ignore_errors: yes
      args:
        chdir: /var/www/node-app

    - name: Start the application with PM2
      shell: >
        DB_HOST={{ rds_endpoint }} 
        REDIS_HOST={{ redis_endpoint }} 
        PORT=3000 
        pm2 start index.js --name backend-app --update-env
      args:
        chdir: /var/www/node-app